name: Build, Push & Validate Infra

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: my-fastapi-app-app-repo

permissions:
  id-token: write # OIDC認証に必要な権限
  contents: read  # リポジトリのコードを読み込むための権限

jobs:
  # ======================================================================
  # Job 1: DockerイメージのビルドとECRへのプッシュ
  # ======================================================================
  build_and_push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- AWS認証 (OIDC) ---
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_PUSH_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # --- ECRへのログイン ---
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- Dockerイメージのビルドとプッシュ (X86_64アーキテクチャ) ---
      - name: Build and push Docker image (X86_64)
        run: |
          # buildx を使用してマルチプラットフォームビルド環境をセットアップ
          docker buildx create --use
          docker buildx inspect --bootstrap

          # X86_64 (linux/amd64) 用にビルドし、直接ECRにプッシュ
          # ${{ github.sha }} は、コミットハッシュを表すGitHub Actionsの組み込み変数。一意なタグとして利用。
          # latest タグもプッシュして、ECSサービスが常に最新を参照できるようにする。
          docker buildx build --platform linux/amd64 -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} --push .
          docker buildx build --platform linux/amd64 -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest --push .


  # ======================================================================
  # Job 2 : Terraformのセットアップとバリデーション
  # ======================================================================
  validate_infra:
    name: Validate Infrastructure Code
    runs-on: ubuntu-latest
    needs: build_and_push # build_and_push ジョブが成功したら実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- AWS認証 (OIDC) for Terraform ---
      # TF_DEPLOY_ROLE_ARN を使う (TFのplan/apply権限を持つロール)
      - name: Configure AWS Credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TF_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # --- Terraformのセットアップ ---
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # --- Terraform init ---
      - name: Terraform init
        run: terraform init

      # --- Terraform validate (コードの構文チェック) ---
      - name: Terraform validate
        run: terraform validate